entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

tls:
  certificates:
    - certFile: "./certificates/traefik.crt"
      keyFile: "./certificates/traefik.key"

api:
  dashboard: true
